const D=window.MEGURU,S=D.spots,C=D.chapters,$=(q,e=document)=>e.querySelector(q),$$=(q,e=document)=>[...e.querySelectorAll(q)];
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem("mi_"+k))??d}catch{return d}},put=(k,v)=>localStorage.setItem("mi_"+k,JSON.stringify(v));
let read=get("read"),visited=get("visited"),memos=get("memos"),filter="すべて",map,marks=[];
function period(){let h=new Date().getHours();return h<10?"morning":h<17?"day":"evening"}
function periodName(){return({morning:"朝",day:"昼",evening:"夕方",rain:"雨"})[period()]}
const greetings={morning:["おはよう。朝の今治には、まだ誰にも読まれていない物語があるよ。"],day:["こんにちは。気になる場所を一つ選んで、ゆっくり読んでみよう。"],evening:["今日見た景色を、あなた自身の言葉で旅帳に残してみない？"]};
function greet(){let a=greetings[period()];$("#greeting").textContent=a[Math.floor(Math.random()*a.length)]}
function save(){put("read",read);put("visited",visited);put("memos",memos);counts()}
function counts(){$("#readN").textContent=read.length;$("#visitN").textContent=visited.length;$("#memoN").textContent=memos.length}
function esc(s=""){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(s){let t=$("#toast");t.textContent=s;t.classList.add("on");clearTimeout(t.x);t.x=setTimeout(()=>t.classList.remove("on"),1800)}
function card(s){return `<article class="story-card" data-story="${s.id}"><div class="art">${s.emoji}</div><div class="content"><span class="tag">${s.category}・${s.area}</span><h3>${s.name}</h3><p>${s.lead}</p><button>${periodName()}の物語を読む →</button></div></article>`}
function bind(e=document){$$("[data-story]",e).forEach(x=>x.onclick=()=>openStory(x.dataset.story))}
function renderToday(id){let s=id?S.find(x=>x.id===id):S[Math.floor(Math.random()*S.length)];$("#today").innerHTML=card(s);bind($("#today"))}
function renderPreview(){$("#chapterPreview").innerHTML=C.slice(0,4).map(c=>`<article class="chapter-card"><div style="font-size:2.4rem">${c.emoji}</div><small>${c.subtitle}</small><h2>${c.title}</h2><p>${c.ending}</p><button class="primary" data-chapter="${c.id}">章をひらく</button></article>`).join("");bindChapters()}
function renderFilters(){let cats=["すべて",...new Set(S.map(s=>s.category))];$("#filters").innerHTML=cats.map(x=>`<button class="${filter===x?"active":""}" data-filter="${x}">${x}</button>`).join("");$$("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderFilters();renderStories()})}
function renderStories(){let q=$("#q").value.trim().toLowerCase();let a=S.filter(s=>(filter==="すべて"||s.category===filter)&&(!q||[s.name,s.area,s.category,s.lead,s.facts].join(" ").toLowerCase().includes(q)));$("#storyGrid").innerHTML=a.length?a.map(card).join(""):`<div class="empty">物語が見つかりませんでした。</div>`;bind($("#storyGrid"))}
function toggle(a,id){let i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);save()}
function openStory(id,weather=false){let s=S.find(x=>x.id===id),key=weather?"rain":period();if(!read.includes(id)){read.push(id);save()}let next=s.next.map(n=>S.find(x=>x.id===n)).filter(Boolean);
$("#storyBody").innerHTML=`<div class="dialogart">${s.emoji}</div><div class="dialogbody"><span class="tag">${s.category}・${s.area}</span><h1>${s.name}</h1><p><b>${weather?"雨の日":periodName()}の物語</b></p><div class="storytext">${s.stories[key]}</div><p class="facts">${s.facts}</p><p><b>ここで見つけるもの</b><br>${s.notice}</p><p class="minatoline"><b>みなと：</b>${s.minato}</p>${next.length?`<p><b>次の物語</b><br>${next.map(x=>`<button data-next="${x.id}">${x.name}</button>`).join(" ")}</p>`:""}<div class="actions"><button id="rainStory">${weather?"現在の時間":"雨の日"}の物語</button><button id="visit" class="${visited.includes(id)?"on":""}">${visited.includes(id)?"✓ 訪問済み":"訪問済みにする"}</button><button id="mapIt">地図</button><button id="official">公式情報</button><button id="closeStory">閉じる</button></div></div>`;
$("#rainStory").onclick=()=>openStory(id,!weather);$("#visit").onclick=()=>{toggle(visited,id);openStory(id,weather);toast("訪問記録を更新しました")};$("#mapIt").onclick=()=>{$("#storyDialog").close();page("map");setTimeout(()=>{initMap();map.setView([s.lat,s.lng],14)},150)};$("#official").onclick=()=>window.open(s.official,"_blank","noopener");$("#closeStory").onclick=()=>$("#storyDialog").close();$$("[data-next]").forEach(b=>b.onclick=()=>openStory(b.dataset.next));$("#storyDialog").showModal()}
function renderChapters(){$("#chapterList").innerHTML=C.map(c=>`<article class="chapter-card"><div style="font-size:2.8rem">${c.emoji}</div><small>${c.subtitle}</small><h2>${c.title}</h2><div class="steps">${c.spots.map((id,i)=>`<span>${i+1}. ${S.find(s=>s.id===id).name}</span>`).join("")}</div><p>${c.ending}</p><button class="primary" data-chapter="${c.id}">地図と物語をひらく</button></article>`).join("");bindChapters()}
function bindChapters(){$$("[data-chapter]").forEach(b=>b.onclick=()=>{let c=C.find(x=>x.id===b.dataset.chapter);page("map");setTimeout(()=>{initMap();let bounds=L.latLngBounds(c.spots.map(id=>{let s=S.find(x=>x.id===id);return[s.lat,s.lng]}));map.fitBounds(bounds,{padding:[35,35]});toast(c.title)},180)})}
function initMap(){if(map){setTimeout(()=>map.invalidateSize(),80);return}map=L.map("leaflet").setView([34.12,133.01],10);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);marks=S.map(s=>L.marker([s.lat,s.lng]).addTo(map).bindPopup(`<b>${s.emoji} ${s.name}</b><br>${s.lead}<br><button onclick="openMapStory('${s.id}')">物語を読む</button>`))}
window.openMapStory=openStory;
function locate(){if(!navigator.geolocation)return toast("位置情報を利用できません");$("#locStatus").textContent="現在地を確認しています…";navigator.geolocation.getCurrentPosition(p=>{initMap();let ll=[p.coords.latitude,p.coords.longitude];L.circleMarker(ll,{radius:9}).addTo(map).bindPopup("現在地").openPopup();map.setView(ll,13);$("#locStatus").textContent="現在地を表示しました"},()=>{$("#locStatus").textContent="位置情報を取得できませんでした"},{enableHighAccuracy:true,timeout:10000})}
function page(id){$$(".page").forEach(p=>p.classList.toggle("active",p.id===id));$$("nav [data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===id));window.scrollTo({top:0,behavior:"smooth"});closeDrawer();if(id==="map")setTimeout(initMap,50);if(id==="journal")renderJournal()}
function journalCards(ids){return ids.length?`<div id="storyGrid">${ids.map(id=>card(S.find(s=>s.id===id))).join("")}</div>`:`<div class="empty">まだ記録がありません。</div>`}
function renderJournal(tab=$(".tabs .active")?.dataset.tab||"read"){$$(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));if(tab==="read")$("#journalBody").innerHTML=journalCards(read);if(tab==="visited")$("#journalBody").innerHTML=journalCards(visited);if(tab==="memo")$("#journalBody").innerHTML=`<div class="memoform card"><input id="mt" placeholder="今日の場所"><textarea id="mm" rows="4" placeholder="心に残ったこと"></textarea><button id="ms" class="primary">旅帳に残す</button></div>${memos.map((m,i)=>`<article class="memo card"><h3>${esc(m.title)}</h3><p>${esc(m.text)}</p><small>${m.date}</small> <button data-del="${i}">削除</button></article>`).join("")}`;bind($("#journalBody"));if(tab==="memo"){$("#ms").onclick=()=>{let title=$("#mt").value.trim(),text=$("#mm").value.trim();if(!title&&!text)return toast("言葉を入力してください");memos.unshift({title:title||"旅の記憶",text,date:new Date().toLocaleDateString("ja-JP")});save();renderJournal("memo");toast("旅帳に残しました")};$$("[data-del]").forEach(b=>b.onclick=()=>{memos.splice(+b.dataset.del,1);save();renderJournal("memo")})}}
function openDrawer(){$("#drawer").classList.add("open");$("#shade").classList.add("show")}function closeDrawer(){$("#drawer").classList.remove("open");$("#shade").classList.remove("show")}
document.addEventListener("click",e=>{let b=e.target.closest("[data-page]");if(b)page(b.dataset.page)});
$("#menu").onclick=openDrawer;$("#close").onclick=closeDrawer;$("#shade").onclick=closeDrawer;$("#speak").onclick=greet;$("#randomStory").onclick=()=>renderToday();$("#q").oninput=renderStories;$("#locate").onclick=locate;
$$(".tabs button").forEach(b=>b.onclick=()=>renderJournal(b.dataset.tab));$("#fab").onclick=()=>{$("#minatoText").textContent=greetings[period()][0];$("#minatoDialog").showModal()};$("#minatoDialog .x").onclick=()=>$("#minatoDialog").close();
$$("[data-help]").forEach(b=>b.onclick=()=>{let f={view:"絶景",history:"歴史",food:"グルメ",rest:"癒やし"}[b.dataset.help];filter=f;$("#minatoDialog").close();page("stories");renderFilters();renderStories()});
$("#reset").onclick=()=>{if(confirm("旅帳の記録をすべて削除しますか？")){read=[];visited=[];memos=[];save();toast("旅帳を初期化しました")}};
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
greet();renderToday();renderPreview();renderFilters();renderStories();renderChapters();counts();